### ISSUE TITLE
nginx : unknown directive "redirectionio_pass" in /etc/nginx/conf.d/default.conf

### ISSUE THREAD

**Issue by vasilvestre** [redirectionio/docker-example#1]
When I'm using your configuration with non-compiled nginx, this error appear.

**Comment by lyrixx** [comment]
Hello, I'm not able to reproduce the error.

I followed the README instructions, and it worked as expected.

Can you double check you ran each commands?

**Comment by lyrixx** [comment]
I am going to close here for now due to the lack of feedback. Please let us know when you have more information and we can consider to reopen.

**Comment by vasilvestre** [comment]
It was probably due to a wrong path to the extension. I tried to make an alpine version of it which complicated the instructions. Anyway using an agent worked and now I'm using the new hosted feature. Thank you for your help !
